# Liens de navigation
#   Pour lier une section d'accueil, utilisez un hash `#` suivi de l'ID de la section.
#   Le paramètre weight définit l'ordre dans lequel les liens apparaissent.

main:
  - name: Projets
    url: /#projects
    weight: 10
  - name: Compétences
    url: /#skills
    weight: 20
  - name: Expérience
    url: /#experience
    weight: 30
  - name: Blog
    url: /#blog
    weight: 40
  - name: Contact
    url: /#contact
    weight: 50
